export const PLANS = [
  {
    id: "free",
    name: "Explorador",
    badge: "Teste grátis/90 dias",
    price: "R$ 0",
    period: "/ mês",
    description: "Para dar os primeiros passos com a Magis sem compromisso.",
    features: [
      "1 template por mês",
      "1 plano por mês",
      "1 download PDF por plano",
      "Sugestões de conteúdo com Magis: BNCC, SAEB e currículo territorial",
      "Editor split-view",
      "Editor de texto livre",
    ],
    available: true,
    cta: "Começar grátis",
    theme: "green" as const,
    featured: false,
  },
  {
    id: "starter",
    name: "Educador",
    badge: "",
    price: "R$ 9,90",
    period: "/ mês",
    description:
      "Para professores que buscam agilidade no planejamento sem abrir mão da qualidade.",
    features: [
      "1 template ativo",
      "2 planos por mês",
      "1 download PDF por plano",
      "Tudo do Explorador",
      "Prioridade no suporte",
      "Histórico completo",
    ],
    available: true,
    cta: "Começar agora",
    theme: "white" as const,
    featured: false,
  },
  {
    id: "medio",
    name: "Mestre",
    badge: "Mais popular",
    price: "R$ 19,90",
    period: "/ mês",
    description: "Para o professor que não abre mão de planejamentos de qualidade.",
    features: [
      "2 templates ativos",
      "4 planos por mês",
      "3 downloads PDF por plano",
      "Tudo do Educador",
      "Organização de templates por escola e turmas",
      "Capacidade aprimorada de sugestões com Magis",
    ],
    available: true,
    cta: "Começar agora",
    theme: "dark" as const,
    featured: true,
  },
  {
    id: "pro",
    name: "Regente",
    badge: "",
    price: "R$ 49,90",
    period: "/ mês",
    description: "Para professores com múltiplas turmas, disciplinas e templates.",
    features: [
      "5 templates ativos",
      "10 planos por mês",
      "3 downloads PDF por plano",
      "Tudo do Mestre",
      "Relatórios de uso",
      "Biblioteca de templates",
      "Memória de contexto ilimitada",
    ],
    available: true,
    cta: "Começar agora",
    theme: "white" as const,
    featured: false,
  },
] as const;

export type Plan = (typeof PLANS)[number];
export type PlanId = Plan["id"];
